apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdrums-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactdrums-client
  template:
    metadata:
      labels:
        app: reactdrums-client
    spec:
      containers:
        - name: reactdrums-client
          image: reactdrums-client:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
