version: '3.8'
services:
  reactdrumsdb:
    container_name: reactdrums-db
    image: postgres:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reactdrumsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
