on: [pull_request]

jobs:
  build: ubuntu-latest
  name: WebPageTest Action
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: WebPageTest
      uses: WPO-Foundation/webpagetest-github-action@main
      with:
        apiKey: ${{ secrets.WPT_API_KEY }}
        urls: https://react-drum-maschine.netlify.app
        label: 'GitHub Action Test'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
